### ISSUE TITLE
yarn is running postinstall from npm package

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/ts2fable#132]
Crap, https://github.com/fable-compiler/ts2fable/pull/129 changes messed up installs Guess I was wrong here: https://github.com/fable-compiler/ts2fable/pull/129#discussion_r153169188

```
C:\Users\camer> yarn global add ts2fable@next
yarn global v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.3: The platform "win32" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
warning ts2fable@0.5.0-build.142: The engine "vscode" appears to be invalid.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ⡀ ts2fable
[-/1] ⡀ waiting...
[-/1] ⡀ waiting...
[-/1] ⡀ waiting...
error C:\Users\camer\AppData\Local\Yarn\config\global\node_modules\ts2fable: Command failed.
Exit code: 1
Command: node ./node_modules/vscode/bin/install
Arguments:
Directory: C:\Users\camer\AppData\Local\Yarn\config\global\node_modules\ts2fable
Output:
module.js:544
    throw err;
    ^

Error: Cannot find module 'C:\Users\camer\AppData\Local\Yarn\config\global\node_modules\ts2fable\node_modules\vscode\bin
    at Function.Module._resolveFilename (module.js:542:15)
    at Function.Module._load (module.js:472:25)
```

**Comment by ctaggart** [comment]
I was wrong. It is trying to run whatever is put in `postinstall`. Great. My first npm package.
```
    "postinstall": "cross-env npm_package_engines_vscode=1.8.1 node ./node_modules/vscode/bin/install"
```
```
error C:\Users\camer\fs\templates\vscode\node_modules\ts2fable: Command failed.
Exit code: 1
Command: cross-env npm_package_engines_vscode=1.8.1 node ./node_modules/vscode/bin/install
Arguments:
Directory: C:\Users\camer\fs\templates\vscode\node_modules\ts2fable
```

**Comment by alfonsogarciacaro** [comment]
Sorry I didn't notice that. Yes, you can add "pre-" or "post-" scripts in the package.json that will be run before or after the specified action.
