### ISSUE TITLE
Error: function with unsupported param array type: ``when``

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/ts2fable#61]
I tried to create bindings for jQuery.

```
PS C:\temp> ts2fable .\node_modules\@types\jquery\index.d.ts Fable.Import.JQuery.fs
unsupported TypeNode kind: 139
unsupported TypeNode kind: 139
unsupported TypeNode kind: 170
unsupported TypeNode kind: 130
unsupported TypeNode kind: 130
unsupported TypeNode kind: 130
unsupported TypeNode kind: 130
unsupported TypeNode kind: 130
unsupported TypeNode kind: 130
unsupported TypeNode kind: 130
unsupported TypeNode kind: 130
unsupported TypeNode kind: 130
unsupported TypeNode kind: 130
unsupported TypeNode kind: 130
unsupported TypeNode kind: 139
unsupported TypeNode kind: 134
unsupported TypeNode kind: 130
unsupported TypeNode kind: 130
unsupported TypeNode kind: 130
unsupported TypeNode kind: 134
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 130
unsupported TypeNode kind: 130
unsupported TypeNode kind: 130
unsupported TypeNode kind: 130
unsupported TypeNode kind: 130
unsupported TypeNode kind: 130
unsupported TypeNode kind: 130
unsupported TypeNode kind: 130
unsupported TypeNode kind: 130
unsupported TypeNode kind: 134
unsupported TypeNode kind: 134
unsupported TypeNode kind: 134
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 95
unsupported TypeNode kind: 130
C:\Users\nojaf\AppData\Roaming\npm\node_modules\ts2fable\dist\fable-core\String.js:153
    throw new Error(x);
    ^

Error: function with unsupported param array type: ``when``
    at arg.cont.x (C:\Users\nojaf\AppData\Roaming\npm\node_modules\ts2fable\dist\fable-core\String.js:153:11)
    at printer (C:\Users\nojaf\AppData\Roaming\npm\node_modules\ts2fable\dist\fable-core\String.js:202:16)
    at C:\Users\nojaf\AppData\Roaming\npm\node_modules\ts2fable\dist\ts2fable.js:2003:266
    at reverse (C:\Users\nojaf\AppData\Roaming\npm\node_modules\ts2fable\dist\fable-core\List.js:73:69)
    at fold (C:\Users\nojaf\AppData\Roaming\npm\node_modules\ts2fable\dist\fable-core\Seq.js:361:13)
    at map (C:\Users\nojaf\AppData\Roaming\npm\node_modules\ts2fable\dist\fable-core\List.js:73:32)
    at printFunction (C:\Users\nojaf\AppData\Roaming\npm\node_modules\ts2fable\dist\ts2fable.js:2002:30)
    at printModule (C:\Users\nojaf\AppData\Roaming\npm\node_modules\ts2fable\dist\ts2fable.js:2089:82)
    at C:\Users\nojaf\AppData\Roaming\npm\node_modules\ts2fable\dist\ts2fable.js:2236:5
    at fold (C:\Users\nojaf\AppData\Roaming\npm\node_modules\ts2fable\dist\fable-core\Seq.js:437:18)
```

Versions:
```
"_id": "ts2fable@0.2.0",
"@types/jquery": "^3.2.16",
```

**Comment by ctaggart** [comment]
Thanks for the report @nojaf, I'll have a look.

**Comment by ctaggart** [comment]
I can make it so ts2fable finishes, but there will be some `TODO` generated lines that are invalid. I don't know how to manually map this. Could use some help.
``` ts
    interface PromiseBase<TR, TJ, TN,
        UR, UJ, UN,
        VR, VJ, VN,
        SR, SJ, SN> extends _Promise<TR>, PromiseLike<TR> {
        /**
         * Add handlers to be called when the Deferred object is either resolved or rejected.
         *
         * @param alwaysCallback A function, or array of functions, that is called when the Deferred is resolved or rejected.
         * @param alwaysCallbacks Optional additional functions, or arrays of functions, that are called when the Deferred is resolved or rejected.
         * @see {@link https://api.jquery.com/deferred.always/}
         * @since 1.6
         */
        always(alwaysCallback: TypeOrArray<Deferred.CallbackBase<TR | TJ, UR | UJ, VR | VJ, SR | SJ>>,
               ...alwaysCallbacks: Array<TypeOrArray<Deferred.CallbackBase<TR | TJ, UR | UJ, VR | VJ, SR | SJ>>>): this;
        /**
         * Add handlers to be called when the Deferred object is resolved.
         *
         * @param doneCallback A function, or array of functions, that are called when the Deferred is resolved.
         * @param doneCallbacks Optional additional functions, or arrays of functions, that are called when the Deferred is resolved.
         * @see {@link https://api.jquery.com/deferred.done/}
         * @since 1.5
         */
        done(doneCallback: TypeOrArray<Deferred.CallbackBase<TR, UR, VR, SR>>,
             ...doneCallbacks: Array<TypeOrArray<Deferred.CallbackBase<TR, UR, VR, SR>>>): this;
        /**
         * Add handlers to be called when the Deferred object is rejected.
         *
         * @param failCallback A function, or array of functions, that are called when the Deferred is rejected.
         * @param failCallbacks Optional additional functions, or arrays of functions, that are called when the Deferred is rejected.
         * @see {@link https://api.jquery.com/deferred.fail/}
         * @since 1.5
         */
        fail(failCallback: TypeOrArray<Deferred.CallbackBase<TJ, UJ, VJ, SJ>>,
             ...failCallbacks: Array<TypeOrArray<Deferred.CallbackBase<TJ, UJ, VJ, SJ>>>): this;
```

**Comment by ctaggart** [comment]
@nojaf, can you try the latest @next? I just uploaded it.
```
yarn global add ts2fable@next
ts2fable node_modules/@types/jquery/index.d.ts Fable.Import.JQuery.fs
```
If you know how to map the "TODO"s, please let me know.

**Comment by nojaf** [comment]
I tried the @next version and indeed those TODO's look complicated.
To be quite frank this is good enough for now. I can move on with my project if I just remove all the lines that have todo in it. Close enough, works for me.

**Comment by alfonsogarciacaro** [comment]
@ctaggart Is it not possible to just use the attribute like `[<ParamArray>] alwaysCallbacks: TypeOrArray<Deferred.CallbackBase<_>>>[]`? Fable supports it.
